version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          POSTGRES_PASSWORD: postgres
          RAILS_ENV: development
      
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: development
          POSTGRES_PASSWORD: postgres

    working_directory: ~/caccs.io

    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - run:
          name: Install environment dependencies
          command: sudo apt-get install -y cmake

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: Bundle Install
          command: bundle check || bundle install --path vendor/bundle

      - run:
          name: Ruby Lang
          command: |
            export LANG=C.UTF-8
            ruby -e 'puts Encoding.default_external'

      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      # - run:
      #     name: Wait for DB
      #     command: dockerize -wait tcp://localhost:5432 -timeout 1m
        
      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load --trace
      - run: bundle exec rake db:migrate

      - run:
          name: Install chrome headless
          command: |
            wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P ~/
            sudo dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb
            sudo apt-get -f install -y
            sudo dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb
            sudo rm /usr/local/bin/chromedriver
            wget -N https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip -P ~/
            unzip ~/chromedriver_linux64.zip -d ~/
            rm ~/chromedriver_linux64.zip
            sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
            sudo chown root:root /usr/local/bin/chromedriver
            sudo chmod 0755 /usr/local/bin/chromedriver

      - type: shell
        name: RSpec
        command: bundle exec rspec

      - run:
          name: Pronto
          command: |
            export PRONTO_PULL_REQUEST_ID="$(echo $CIRCLE_PULL_REQUEST | grep -o -E '[0-9]+')"
            export PRONTO_GITHUB_SLUG="${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
            export PRONTO_FORMAT="%{msg} [%{runner}:%{level}]"
            export PRONTO_VERBOSE=true
            bundle exec pronto run -f github_pr github_status -c origin/master

      - run:
          name: Danger
          command: |
            bundle exec rake assets:precompile
            bundle exec danger

      - store_artifacts:
          path: tmp/test_results
